export default function signatureList(params: any) {
  return [
    {
      index: 0,
      label: "Intro Invite <IM>",
      value: "quick_call_follow_up_intro_invite",
      subject: "Intro Meeting Invite",
      folder_name: "IM Invite",
      attachment_files: ['Beginning w-EIM', 'What I Offer', 'Feed List Template'],
      html: `<p>Hi {{name}},</p><p><br></p><p>It was great chatting with you. As I said on the phone, planning is more about options than money.</p><p><br></p><p>During our meeting, I will SHOW you how I help my clients Live Their Best Lives through balance. All that I require you to bring is an Open Heart and Mind. The rest we will figure out along the way.</p><p><br></p><p>I have also attached a list of priorities people typically think about prior to our meeting as well as a little information about me. Be sure to click on a few of the links AND videos in the document to get an intro to some of the "tools" that support my planning philosophy.</p><p><br></p><p>Should you have any questions, feel free to contact me directly. I look forward to the meeting.</p><p><br></p><p>Thanks so much!</p><br><p>Randy Jones</p><p>The Legacy Builder</p><p>Office: 571-375-8031</p><p>Cell: 703-919-6258</p>`,
    },
    {
      index: 1,
      label: "G.A.P. Invite <ASMNT>",
      value: "intro_follow_up_gap_invite",
      subject: "Goals, Assess, Plan (GAP) Meeting Invite",
      folder_name: "GAP Invite",
      attachment_files: ['Goals Sheet','The Legacy System I','3 Phases','Confidential Questionnaire & Docs List'],
      html: `<p>Hi {{name}},</p><p><br></p><p>When it comes to building any plan, it is imperative that we have a Goal. Your Goal is the destination or where you want the plan to take you. Attached is:</p><p><br></p><p>A Recap of the slides</p><p>The Documents list</p><p>The Synergy coaching agreement</p><p>Confidential client questionnaire</p><p>The Goals sheet</p><p><br></p><p>During our meeting, we will use your answers on your Goals sheet to start developing your roadmap. Please upload your documents to your secure folder: Client Folder</p><p><br></p><p>Let me know if you have any questions.</p><br><p>Randy Jones</p><p>The Legacy Builder</p><p>Office: 571-375-8031</p><p>Cell: 703-919-6258</p>`,
    },
    {
      index: 2,
      label: "Risk Management Invite <RM>",
      value: "goals_assess_plan_follow_up_risk_management_invite",
      subject: "Risk Management Meeting Invite",
      folder_name: "Risk Management Invite",
      attachment_files: ['DRAFT-Safe vs Risk Growth','Client Quik App - Fillable','Introducing XXX & Taking Apps and Exams'],
      html: `<p>Hi {{name}},</p><br><p>During the last meeting, we discussed how your Wealth Portfolio is a combination of your savings rate and the amount of Safety/Guarantee vs Market Risk/Volatility you want in your overall plan. Attached is a copy of your Plan A &amp; B summary.</p><p>During our next meeting, we will discuss protecting your #1 Asset, the 8 Risks to your Cash Flow, and the numbers of how to protect your “Todays” without sacrificing your “Tomorrows” at the same time. Let me know if you have any questions.</p><p>Talk to you soon.</p><br><p>Sincerely,</p><br><p>Randy Jones</p><p>The Legacy Builder</p><p>Office: 571-375-8031</p><p>Cell: 703-919-6258</p>`,
    },
    {
      index: 3,
      label: "Wealth Accum & Distro Invite <WA & WD>",
      value: "threat_options_follow_up_wealth_accum_distro_invite",
      subject: "Wealth Accumulation Meeting Invite",
      folder_name: "Wealth Accumulation Invite",
      attachment_files: ['8 Risk','Free Market Investing'],
      html: `<p>Hi {{name}},</p><br><p>We covered A LOT in our last meeting about how we will protect your <strong>#1 Asset</strong> from the <strong>8 Major Risks</strong>. (See attached) During this meeting, we'll go through the numbers and how they will:</p><p>Attached are the numbers of how we will use a <strong>whole life policy</strong> in conjunction with a <strong>term policy</strong> and your <strong>LEAF Spending Plan</strong> to:</p><ul><li><strong>Have One dollar do multiple jobs</strong> when protecting against the <strong>8 Major Risks.</strong></li><li><strong>Lower your taxes and risks</strong></li><li><strong>Provide some permanent life insurance,</strong></li><li><strong>Potentially provide long-term care benefits and,</strong></li><li><strong>Access to tax-free income</strong></li><li><strong>Transform your debt into Wealth.</strong></li><li><strong>Accelerate the Growth and Access of your other Assets</strong></li></ul><p>Liz will reach out to you to update your <strong>Life and Disability applications</strong> as well as to make the intro to <strong>&lt;P&C partner&gt;</strong>. Attached is your revised <strong>Safe/Risk Numbers</strong>.</p><p><strong>Next Meeting:</strong></p><p>Now that we have some safe, guaranteed growth, it's time to discuss how we will structure the "risk" portion of your <strong>Wealth Portfolio</strong> as well as do a check-in on your <strong>Spending Plan</strong> and <strong>MINT</strong>.</p><p>I have also included your updated <strong>Spending Plan and Wealth Accelerator</strong> for your use. Let me know if you have any questions.</p><p>Thanks so much,</p><br><p>Sincerely,</p><br><p>Randy Jones</p><p>The Legacy Builder</p><p>Office: 571-375-8031</p><p>Cell: 703-919-6258</p>`,
    },
    {
      index: 4,
      label: "Wealth Transfer Invite <WT>",
      value: "invest_annuity_follow_up_wealth_transfer_invite",
      subject: "Wealth Transfer Meeting Invite",
      folder_name: "Wealth Transfer Invite",
      attachment_files: ['Annuity Plain and Simple','EY White Paper','Harvard Review of Annuities'],
      html: `<p>Hi {{name}},</p><br><p>During the last meeting, we discussed how your <strong>Legacy System</strong> will be a “resource” for your Todays and your Tomorrows. Hopefully by now, you <strong>SEE</strong> how saving first and spending what’s left can help us find the money to transform your debt into <strong>Wealth</strong>.</p><p>During this meeting we will discuss your estate, and the legal docs associated with it. “The goal is not to live forever but to create something that will last forever.”</p><p>I look forward to speaking with you.</p><br><p>Randy Jones</p><p>The Legacy Builder</p><p>Office: 571-375-8031</p><p>Cell: 703-919-6258</p>`,
    },
    {
      index: 5,
      label: "Annual Review Invite <AR>",
      value: "wealth_transfer_follow_up_annual_review_invite",
      subject: "Annual Review Meeting Invite",
      folder_name: "Annual Review (AR) Invite",
      attachment_files: ['The Annual Review', 'The Renewal Language'],
      html: `<p>Hi {{name}},</p><br><p>I hope you are having a great day! I wanted to reach out because <strong>It Is Time For Us To Get Back Together</strong> to finish implementing your plan. The purpose of planning is to maximize income today and tomorrow (retirement) with the ability to access cash when you need it. Over time, the <strong>Whys, What's, and How’s</strong> can become blurred.</p><p>Click the link below and let me know which dates work best to do a review: <a href="${params?.link}">${params?.linkText ?? 'Schedule a Review'}</a></p><p>I look forward to our next conversation.</p><br><p>Randy Jones</p><p>The Legacy Builder</p><p>Office: 571-375-8031</p><p>Cell: 703-919-6258</p>`,
    },
  ];
}
