<script setup lang="ts">
    const toast = useToast()
    const route = useRoute()
    const router = useRouter()
    const meetingId = route.params.id as string
    console.log('Meeting ID:', meetingId)
    const isLoading = ref(true)
    const isLoadingAi = ref(false)
    const notes = ref<any[]>([])

    const { data }: any = await useFetch('/api/pipedrive/all_person')
    console.log('all_person:', data.value)
    const contactList = ref<any[]>(data.value?.response?.data || [])
    const selectedContact = ref<any>(null);
    const meetingTypeList = ref<any[]>([])
    const selectedMeetingType = ref<any>(null);

    const ai_summary = ref<any>(null);
    const meetingDetail = ref<any>(null);
    const nextMeeting = ref<any>(null);
    const nextScheduleMeeting = ref<any>(null);

    import { ref } from 'vue'
    import { z } from 'zod'

    /**
     * Zod schema (optional but good practice)
     * Useful for validation if needed.
     */
    const schema = z.object({
        meeting_host_id: z.string(),
        meeting_host_email: z.string().email(),
        meeting_uuid: z.string(),
        meeting_id: z.number(),
        meeting_topic: z.string(),
        meeting_start_time: z.string(),
        meeting_end_time: z.string(),
        summary_start_time: z.string(),
        summary_end_time: z.string(),
        summary_created_time: z.string(),
        summary_last_modified_time: z.string(),
        summary_title: z.string(),
        summary_overview: z.string(),
        summary_doc_url: z.string().url(),
        summary_details: z.array(z.object({
            label: z.string(),
            summary: z.string()
        })),
        next_steps: z.array(z.string()),
        summary_content: z.string(),
        ai_summary_overview: z.string().optional()
    })

    onMounted(async () => {
        meetingTypeList.value = leafProcess()
        // console.log('meetingTypeList:', meetingTypeList.value)
        selectedMeetingType.value = meetingTypeList.value.length ? meetingTypeList.value[0].value : null;
        selectedContact.value = contactList.value.length ? contactList.value[0].id : null;
        const { response: _notes } = await getNotes()
        if (_notes?.data?.length) {
            notes.value = _notes.data.filter((note: any) => note.content?.includes('generated by AI')) || []
        }

        const { response } = await getMeetingDetail()
        // console.log('Fetched data:', response)
        meetingDetail.value = response
        const nextMeetingDate = getRandomDayFromNext7()
        // console.log('Next Meeting Date:', nextMeetingDate)
        nextScheduleMeeting.value = nextMeetingDate.trim()
        form.value.meeting_host_email = response.meeting_host_email;
        form.value.summary_title = response.summary_title;
        form.value.summary_overview = response.summary_overview + ` Next meeting date is ${nextMeetingDate}`;

        const { response: summary_overview } = await generateSummary()
        // console.log('Generated Summary:', summary_overview)
        ai_summary.value = summary_overview;
        
        const { response: next_meeting } = await getNextMeeting(nextMeetingDate)
        // console.log('Next Meeting:', next_meeting)
        nextMeeting.value = next_meeting;

        await handleMeetingSummary()

        isLoading.value = false
    })

    const form = ref({
        meeting_host_id: '',
        meeting_host_email: '',
        meeting_uuid: '',
        meeting_id: 0,
        meeting_topic: '',
        meeting_start_time: '',
        meeting_end_time: '',
        summary_start_time: '',
        summary_end_time: '',
        summary_created_time: '',
        summary_last_modified_time: '',
        summary_title: '',
        summary_overview: '',
        summary_doc_url: '',
        summary_details: [],
        next_steps: [],
        summary_content: '',
        ai_summary_overview: ''
    })

    async function handleMeetingSummary() {
        isLoadingAi.value = true

        const today = new Date();
        const formatted = today.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit' });

        const current_meeting_type = meetingTypeList.value.find(item => item.value === selectedMeetingType.value)?.label || 'Quick Call'
        let meeting_end_time: any = new Date(meetingDetail.value.meeting_end_time);

        const current_meeting_index = meetingTypeList.value.findIndex(item => item.value === selectedMeetingType.value);

        const next_meeting_type = meetingTypeList.value[current_meeting_index + 1]?.label || 'Intro';
        let next_meeting_content = nextMeeting.value.choices[0].message.content?.length < 10 ? nextScheduleMeeting.value : nextMeeting.value.choices[0].message.content
        // console.log('Next Meeting Content Length:', next_meeting_content)

        meeting_end_time = meeting_end_time.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit' });
        let add_note_date = `${formatted} - Did ${current_meeting_type} last ${meeting_end_time} \n`
        add_note_date += `${formatted} - Set ${next_meeting_type} - ${next_meeting_content} \n`;
        add_note_date += `************************************************************* \n\n`
        const marked_as_ai = ` \n\n***This was generated by AI***`
        let content = ai_summary.value.choices[0].message.content?.trim()
        // console.log('Summary Content Length:', content)
        if (content.length < 10) {
            content = form.value.summary_overview;
        }
        form.value.ai_summary_overview = add_note_date + content + marked_as_ai;

        isLoadingAi.value = false
    }

    async function onSubmit() {
        if (selectedContact.value === null) {
            toast.add({
                title: 'No Contact Selected',
                description: 'Please select a contact before adding the note.',
                color: 'warning'
            })
            return;
        }

        if (selectedMeetingType.value === null) {
            toast.add({
                title: 'No Meeting Type Selected',
                description: 'Please select a meeting type before adding the note.',
                color: 'warning'
            })
            return;
        }

        // console.log('Submitted Data:', form.value)
        form.value.ai_summary_overview = form.value.ai_summary_overview.replace(/\n/g, '<br>');
        console.log('notes.value:', notes.value)
        // If notes exist, update the first one; otherwise, add a new note
        if (notes.value.length) {
            const new_note = form.value.ai_summary_overview + "*** <br><br>" + notes.value[0].content
            // console.log('New Note Content:', new_note)
            const { response } = await updateNote({...notes.value[0], new_note})
            // console.log('updateNote:', response)
        } else {
            const { response } = await addNote()
            // console.log('addNote:', response)
        }

        toast.add({
            title: 'Note added successfully',
            description: 'AI-generated summary has been added successfully.',
            color: 'success'
        })

        setTimeout(() => {
            router.back()
        }, 1000)
    }

    async function getMeetingDetail() {
        const response = await fetch('/api/zoom/meeting_detail', {
            method: 'POST',
            body: JSON.stringify({meetingId})
        })
        const res = await response.json()

        return res
    }

    async function generateSummary() {
        const response = await fetch('/api/openrouterai/meeting_summary', {
            method: 'POST',
            body: JSON.stringify({
                filterObj: {
                    summary_overview: form.value.summary_overview,
                    next_steps: form.value.next_steps
                }
            })
        })
        const res = await response.json()

        return res
    }

    async function getNextMeeting(nextMeetingDate: string) {
        
        const response = await fetch('/api/openrouterai/next_meeting', {
            method: 'POST',
            body: JSON.stringify({
                filterObj: {
                    summary_overview: form.value.summary_overview + ' Next meeting date is ' + nextMeetingDate
                }
            })
        })
        const res = await response.json()

        return res
    }

    async function updateNote(note: any) {
        const response = await fetch('/api/pipedrive/update_note', {
            method: 'PUT',
            body: JSON.stringify({
                new_note: note.new_note,
                id: note.id
            })
        })
        const res = await response.json()

        return res
    }

    async function addNote() {
        const response = await fetch('/api/pipedrive/add_note', {
            method: 'POST',
            body: JSON.stringify({
                ai_summary_overview: form.value.ai_summary_overview,
                person_id: selectedContact.value,
                org_id: 1
            })
        })
        const res = await response.json()

        return res
    }

    async function getNotes() {
        const response = await fetch('/api/pipedrive/all_notes', {
            method: 'POST',
            body: JSON.stringify({
                person_id: selectedContact.value,
                pinned_to_person_flag: 1,
            })
        })
        const res = await response.json()

        return res
    }

    async function handleSelectContact(value: any) {
        // console.log('Selected Contact ID:', selectedContact.value);
        const { response: _notes } = await getNotes()
        if (_notes?.data?.length) {
            notes.value = _notes.data.filter((note: any) => note.content?.includes('generated by AI')) || []
        } else {
            notes.value = []
        }
    }

    async function handleSelectMeetingType(value: any) {
        // console.log('Selected Meeting Type ID:', selectedMeetingType.value);
        await handleMeetingSummary()
    }
</script>

<template>
    <UiAppLoading
        v-if="isLoading"
        class="w-full border rounded-md p-6 my-4 border-neutral-800"
    />
    <UDashboardPanel v-if="!isLoading" id="meeting-details" :ui="{ body: 'gap-2 sm:gap-2' }">
        <template #header>
            <UDashboardNavbar title="Meeting Summary Details">
                <template #leading>
                    <UDashboardSidebarCollapse />
                </template>
                <template #right>
                    <UiAppButtonBack />
                </template>
            </UDashboardNavbar>
        </template>
        <template #body>
            <div v-if="!form.summary_overview" class="p-6">
                <div class="w-full border rounded-md p-6 my-4 border-neutral-800">
                    No summary overview available for this meeting.
                </div>                
            </div>
            <div v-else class="p-6 space-y-8">
                <UForm :state="form" :schema="schema" @submit="onSubmit" class="space-x-6 flex">
                    <!-- Summary Info -->
                    <UCard class="w-full">
                        <template #header>
                            <h2 class="text-lg font-semibold">Meeting Details</h2>
                        </template>
                        <div class="grid grid-cols-1 gap-4">
                            <UInput v-model="form.meeting_host_email" label="Meeting Host Email" />
                            <UInput v-model="form.summary_title" label="Summary Title" />
                            <UTextarea v-model="form.summary_overview" label="Overview" :rows="15" />
                        </div>
                    </UCard>

                    <!-- Summary Details (Array) -->
                    <UCard class="w-full">
                        <template #header>
                            <h2 class="text-lg font-semibold">AI Generated Summary Details</h2>
                        </template>
                        <div class="grid grid-cols-1 gap-2">
                            <div class="w-full space-y-2">
                                <label class="block text-sm font-medium w-50 my-auto">Contacts:</label>
                                <USelect
                                    v-model="selectedContact"
                                    :items="contactList.map(item => ({ value: item.id, label: item.name }))"
                                    placeholder="Choose a contact"
                                    class="w-full"
                                    @update:modelValue="handleSelectContact"
                                />
                            </div>
                            <div class="w-full space-y-2">
                                <label class="block text-sm font-medium w-50 my-auto">Meeting Type:</label>
                                <USelect
                                    v-model="selectedMeetingType"
                                    :items="meetingTypeList"
                                    placeholder="Choose a meeting type"
                                    class="w-full"
                                    @update:modelValue="handleSelectMeetingType"
                                />
                            </div>
                            <UiAppLoading
                                v-if="isLoadingAi"
                                class="w-full border rounded-md p-6 my-4 border-neutral-800"
                            />
                            <UTextarea v-if="!isLoadingAi" v-model="form.ai_summary_overview" label="Overview" :rows="20" />
                            <span class="text-sm text-gray-500 italic">*Please review and edit the AI-generated summary before adding it as a note.</span>
                        </div>
                        <template #footer>
                            <div class="flex w-full justify-end">
                                <UButton @click="onSubmit" icon="i-lucide-plus" size="lg" color="primary" variant="solid">Add AI Summary as Pipedrive Notes</UButton>
                            </div>
                        </template>
                    </UCard>
                </UForm>
            </div>
        </template>
    </UDashboardPanel>

</template>
